### ISSUE TITLE
Swagger module does not correctly handle string type with date or date-type format

### ISSUE THREAD

**Issue by omusil24** [qorelanguage/qore#2341]
example:
```
definitions:
  Person:
    type: object
    properties:
      birthdate:
        type: string
        format: date
        example: "1987-05-23"
```
